/* Caprate - Units data. available: "Available now" | "Showing scheduled" | "Coming soon". Updated Oct 8 2026 (10 units; photos for 2513 Liberty Heights, 629 Dumbarton D, 511 E 43rd) */
window.CAPRATE_UNITS = [
  {id:"koko2126", address:"2126 Koko Ln", unit:"", beds:3, baths:1, type:"Renovated rowhome", hood:"Panway-Braddish", zip:"21216", features:["Finished basement","Your own front door"], nearby:["Near Mondawmin Metro","Near Coppin State University"], photos:[], available:"Available now", rent:"", accessible:false},
  {id:"dumbartonD", address:"629 Dumbarton Ave", unit:"D", beds:1, baths:1, type:"Rowhome apartment", hood:"Original Northwood", zip:"21218", features:["In-unit laundry","Renovated kitchen"], nearby:["Near Morgan State University","Near The Alameda shops"], photos:["629-dumbarton-d-2.jpg","629-dumbarton-d-1.jpg","629-dumbarton-d-3.jpg","629-dumbarton-d-4.jpg","629-dumbarton-d-5.jpg","629-dumbarton-d-6.jpg","629-dumbarton-d-7.jpg","629-dumbarton-d-8.jpg","629-dumbarton-d-9.jpg","629-dumbarton-d-10.jpg"], available:"Available now", rent:"", accessible:false},
  {id:"e43rd1b", address:"511 E 43rd St", unit:"1B", beds:2, baths:1, type:"Rowhome apartment", hood:"Pen Lucy", zip:"21212", features:["Renovated finishes"], nearby:["Near Loyola University","Near MARC / Penn Line"], photos:["511-e-43rd-3a-1.png","511-e-43rd-3a-2.png","511-e-43rd-3a-3.png","511-e-43rd-3a-4.png","511-e-43rd-3a-5.png","511-e-43rd-3a-6.png","511-e-43rd-3a-7.png"], available:"Available now", rent:"", accessible:false},
  {id:"liberty2513", address:"2513 Liberty Heights Ave", unit:"Bsmt", beds:1, baths:1, type:"Renovated basement apartment", hood:"Forest Park", zip:"21215", features:["Private entrance"], nearby:["Near Mondawmin Metro","Near Forest Park Golf Course"], photos:["2513-liberty-heights-bsmt-3.jpg","2513-liberty-heights-bsmt-1.jpg","2513-liberty-heights-bsmt-2.jpg","2513-liberty-heights-bsmt-4.jpg","2513-liberty-heights-bsmt-5.jpg","2513-liberty-heights-bsmt-6.jpg","2513-liberty-heights-bsmt-7.jpg","2513-liberty-heights-bsmt-8.jpg","2513-liberty-heights-bsmt-9.jpg","2513-liberty-heights-bsmt-10.jpg","2513-liberty-heights-bsmt-11.jpg","2513-liberty-heights-bsmt-12.jpg"], available:"Available now", rent:"", accessible:false},
  {id:"clifton3512_3", address:"3512 Clifton Ave", unit:"3", beds:2, baths:1, type:"Renovated apartment", hood:"Walbrook", zip:"21216", features:["Multi-unit building"], nearby:["Near Mondawmin Metro","Near Coppin State University"], photos:[], available:"Available now", rent:"", accessible:false},
  {id:"clifton3514_1", address:"3514 Clifton Ave", unit:"1", beds:2, baths:1, type:"Renovated apartment", hood:"Walbrook", zip:"21216", features:["Multi-unit building"], nearby:["Near Mondawmin Metro","Near Coppin State University"], photos:[], available:"Available now", rent:"", accessible:false},
  {id:"garrison2905B", address:"2905 Garrison Blvd", unit:"B", beds:2, baths:1, type:"Renovated apartment", hood:"Garwyn Oaks", zip:"21216", features:["On-site laundry","Central A/C"], nearby:["Near Mondawmin Metro","Bus lines 91/15/M2/B"], photos:[], available:"Available now", rent:"", accessible:false},
  {id:"garrison2928B", address:"2928 Garrison Blvd", unit:"B", beds:2, baths:1, type:"Renovated apartment", hood:"Garwyn Oaks", zip:"21216", features:["On-site laundry","Central A/C"], nearby:["Near Mondawmin Metro","Bus lines 91/15/M2/B"], photos:[], available:"Available now", rent:"", accessible:false},
  {id:"allendale2927A", address:"2927 Allendale Rd", unit:"A", beds:2, baths:1, type:"Renovated apartment", hood:"Garwyn Oaks", zip:"21216", features:["On-site laundry","Central A/C"], nearby:["Near Mondawmin Metro","Bus lines 91/15/M2/B"], photos:[], available:"Available now", rent:"", accessible:false},
  {id:"allendale2943B", address:"2943 Allendale Rd", unit:"B", beds:2, baths:1, type:"Renovated apartment", hood:"Garwyn Oaks", zip:"21216", features:["On-site laundry","Central A/C"], nearby:["Near Mondawmin Metro","Bus lines 91/15/M2/B"], photos:[], available:"Available now", rent:"", accessible:false},
];
window.CAPRATE_META = {city:"Baltimore City", updated:"October 8, 2026", phone:"(410) 415-3142", phoneRaw:"4104153142", email:"leasing@capratepropertymgmt.com", contact:"Terry Drake"};
window.dispatchEvent(new Event('caprate:units'));
